name: Auto Release

on:
  push:
    branches:
      - 0.15.0
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel, windows-latest, ubuntu-latest]
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}
      # https://github.com/electron-userland/electron-builder/issues/3179
      USE_HARD_LINKS: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.18.0

      - name: Import Apple Code Signing Certificates
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-15-intel'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CSC_KEY_LINK }}
          p12-password: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Create .env file
        run: |
          echo "SUPA_PROJECT_ID=${{ secrets.SUPA_PROJECT_ID }}" > .env
          echo "SUPA_KEY=${{ secrets.SUPA_KEY }}" >> .env
          echo "AXIOM_TOKEN=${{ secrets.AXIOM_TOKEN }}" >> .env
          echo "AXIOM_ORG_ID=${{ secrets.AXIOM_ORG_ID }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package & Publish (OSX)
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-15-intel'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: npm run package:publish

      - name: Package & Publish (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          GPG_SECRET_KEY_B64: ${{ secrets.GPG_SECRET_KEY_B64 }}
          GPG_SECRET_KEY_PASSWORD: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
        run: npm run package:publish

      - name: Package & Publish (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run package:publish
